// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Presenter is an autogenerated mock type for the Presenter type
type Presenter struct {
	mock.Mock
}

type Presenter_Expecter struct {
	mock *mock.Mock
}

func (_m *Presenter) EXPECT() *Presenter_Expecter {
	return &Presenter_Expecter{mock: &_m.Mock}
}

// Present provides a mock function with given fields: _a0
func (_m *Presenter) Present(_a0 []string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Present")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Presenter_Present_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Present'
type Presenter_Present_Call struct {
	*mock.Call
}

// Present is a helper method to define mock.On call
//   - _a0 []string
func (_e *Presenter_Expecter) Present(_a0 interface{}) *Presenter_Present_Call {
	return &Presenter_Present_Call{Call: _e.mock.On("Present", _a0)}
}

func (_c *Presenter_Present_Call) Run(run func(_a0 []string)) *Presenter_Present_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string))
	})
	return _c
}

func (_c *Presenter_Present_Call) Return(_a0 error) *Presenter_Present_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Presenter_Present_Call) RunAndReturn(run func([]string) error) *Presenter_Present_Call {
	_c.Call.Return(run)
	return _c
}

// NewPresenter creates a new instance of Presenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Presenter {
	mock := &Presenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
