// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

type Producer_Expecter struct {
	mock *mock.Mock
}

func (_m *Producer) EXPECT() *Producer_Expecter {
	return &Producer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function with no fields
func (_m *Producer) Produce() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Producer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type Producer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
func (_e *Producer_Expecter) Produce() *Producer_Produce_Call {
	return &Producer_Produce_Call{Call: _e.mock.On("Produce")}
}

func (_c *Producer_Produce_Call) Run(run func()) *Producer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Producer_Produce_Call) Return(_a0 []string, _a1 error) *Producer_Produce_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Producer_Produce_Call) RunAndReturn(run func() ([]string, error)) *Producer_Produce_Call {
	_c.Call.Return(run)
	return _c
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
